import { Subject } from "@/src/shared/types/subject.type";

export const subject: Subject = {
    title: "Estatística Aplicada",
    introduction: "Esse trabalho realizado tem o intuito de mostrar os conceitos de Estatística Aplicada, e as suas diversas aplicações. Sendo uma das matérias da grade curricular do Curso de Análise e Desenvolvimento de Sistemas na Fatec Carapicuíba, mostra como é importante que o profissional tenha conhecimento sobre a disciplina. Com o intuito de ajudar no processo de aprendizagem escolar, e de concentrar pesquisas sobre este conteúdo.",
    task: "Criar uma página de internet que disponibilize aos alunos de Estatística Aplicada como material de apoio aos seus estudos.",
    description: "Essa atividade foi apresentada como atividade complementar na disciplina de Estatística Aplicada do curso de Análise e Desenvolvimento de Sistemas, ministrada pelo professor Luciano Condori, na Fatec de Carapicuíba. O objetivo é fornecer material de apoio aos alunos inscritos na disciplina.",
    conclusion: "A estatística aplicada oferece um framework robusto para a navegação em um mundo incerto. Iniciando pela amostragem criteriosa, passamos pela descrição detalhada dos dados através de medidas de tendência e dispersão, modelamos relacionamentos com regressão, compreendemos a aleatoriedade com a probabilidade e, finalmente, realizamos inferências precisas com intervalos de confiança. A exclusão de testes de hipóteses e softwares neste relatório permitiu um foco aprofundado na lógica e na matemática que sustentam essas ferramentas. O domínio destes conceitos não é apenas uma competência técnica, mas uma necessidade fundamental para a leitura crítica da realidade científica e social.",
    bibliography: [
        "Estatística - UFSM, https://www.ufsm.br/app/uploads/sites/413/2018/11/04_estatistica.pdf",
        "Apostila de Estatística, https://www.inf.ufsc.br/~vera.carmo/LIVROS/LIVROS/Luis%20Felipe%20Dias%20Lopes.pdf",
        "Amostragem - UFPB DE - DEPARTAMENTO DE ESTATÍSTICA, http://www.de.ufpb.br/~luiz/Adm/Aula9.pdf",
        "Noções de Amostragem -, https://tanoresumo.com.br/nocoes-de-amostragem/",
        "Técnicas de amostragem, https://cesad.ufs.br/ORBI/public/uploadCatalago/14575316022012Estatistica_Aplicada_a_Administracao_Aula_2.pdf",
        "Distribuição de Frequências | PDF - Scribd, https://pt.scribd.com/document/666930025/DISTRIBUICAO-DE-FREQUENCIAS",
        "Tipos de amostragem probabilística e não-probabilística [9 Técnicas] - OPUS | Pesquisa, https://www.opuspesquisa.com/blog/tecnicas/amostragem/",
        "Fundamentos de Estatística - ProEdu, https://proedu.rnp.br/bitstream/handle/123456789/1579/Fundamentos%20de%20Estat%C3%ADstica%20-%20MULTIMEIOS%20-%20CEPA.pdf?sequence=1&isAllowed=y",
        "AULA 1 RESUMO DE DADOS 1 TIPOS DE VARIÁVEIS Em estatística, uma variável é um atributo mensur, https://ead.uepg.br/apl/sigma/assets/editais/PS0042E0002.pdf",
        "Moda, média e mediana: como calculá-las - Brasil Escola, https://brasilescola.uol.com.br/matematica/moda-media-mediana.htm",
        "Média, moda e mediana: qual a diferença e como calcular? - Kumon, https://www.kumon.com.br/blog/matematica/media-moda-e-mediana/",
        "Introdução à estatística: média, mediana e moda (vídeo) - Khan Academy, https://pt.khanacademy.org/math/em-mat-estatistica/x5d13d3b4b5b8c419:medidas-de-tendencia-central/x5d13d3b4b5b8c419:media-mediana-e-moda/v/statistics-intro-mean-median-and-mode",
        "Média, Moda e Mediana - Toda Matéria, https://www.todamateria.com.br/media-moda-e-mediana/",
        "Medidas de Tendência Central e Dispersão | Concise Medical Knowledge - Lecturio, https://www.lecturio.com/pt/concepts/medidas-de-tendencia-central-e-dispersao/",
        "Medidas de dispersão - Toda Matéria, https://www.todamateria.com.br/medidas-de-dispersao/",
        "Medidas de dispersão Introdução Para a compreensão deste capítulo, é necessário que você tenha entendido - Unitins, https://www.unitins.br/BibliotecaMidia/Files/Documento/AVA_633848868383423750estatistica___aula_7.pdf",
        "Resumo das Medidas de Dispersão ISS-BH – Estatística - Estratégia Concursos, https://www.estrategiaconcursos.com.br/blog/medidas-de-dispersao-iss-bh-estatistica/",
        "Medidas de dispersão: variância e desvio padrão - Brasil Escola - UOL, https://brasilescola.uol.com.br/matematica/medidas-dispersao-variancia-desvio-padrao.htm",
        "Intervalos Estatísticos para uma única Amostra - parte II - Intervalo de confiança para proporção - est.ufmg.br, https://est.ufmg.br/~marcosop/est031/aulas/Capitulo_8_2.pdf",
        "Aula 8 – Intervalos de confiança para proporções – amostras grandes, https://aedbest.files.wordpress.com/2012/07/aula-8-intervalos-de-confianc3a7a-para-proporc3a7c3a3o-amostras-grandes.pdf",
        "Correlação e Regressão Linear Simples - RPubs, https://rpubs.com/gleidsonmr/1016194",
        "CORRELAÇÃO LINEAR, TIPOS DE CORRELAÇÃO. REGRESSÃO LINEAR PELO ESTUDO DA CORRELAÇÃO E UTILIZANDO OS MÍNIMOS QUADRADOS, https://cesad.ufs.br/ORBI/public/uploadCatalago/09222427022012Bioestatistica_Aula_10.pdf",
        "Correlação de Pearson: o que é e como interpretar? - Blog Psicometria Online -, https://www.blog.psicometriaonline.com.br/o-que-e-correlacao-de-pearson/",
        "Coeficiente de correlação de Pearson - GP Soluções em Estatística, https://gpestatistica.netlify.app/blog/correlacao/",
        "Regressão linear simples: o ajuste de uma reta - Sonia Vieira, http://soniavieira.blogspot.com/2019/09/parametros-da-regressao-linear-simples.html",
        "Regressão linear – Wikipédia, a enciclopédia livre, https://pt.wikipedia.org/wiki/Regress%C3%A3o_linear",
        "Análise de Regressão 1. Introdução Os modelos de regressão são largamente utilizados em diversas áreas do conhecimento, t, https://docs.ufpr.br/~jomarc/regressao.pdf",
        "Introdução aos modelos de regressão linear, https://repositorio.enap.gov.br/bitstream/1/4788/1/Livro_Regress%C3%A3o%20Linear.pdf",
        "Intervalo de confiança – Wikipédia, a enciclopédia livre, https://pt.wikipedia.org/wiki/Intervalo_de_confian%C3%A7a",
        "Intervalo de Confiança - Pro Educacional, https://proeducacional.com/blogs/aula-gratuita/intervalo-de-confianca",
        "Interpretação de intervalos de confiança : r/AskStatistics - Reddit, https://www.reddit.com/r/AskStatistics/comments/1nrl2ys/interpretation_of_confidence_intervals/?tl=pt-br",
        "ESTIMAÇÃO POR INTERVALO (INTERVALOS DE CONFIANÇA) Cada um dos métodos de estimação pontual permite associar a cada parâme - Sigarra, https://sigarra.up.pt/feup/pt/conteudos_service.conteudos_cont?pct_id=7879&pv_cod=08TE8azoaa58",
        "Intervalo de Confiança para a Média com desvio padrão da população desconhecido (Módulo 2.2.2) - YouTube, https://www.youtube.com/watch?v=fwAQyjPEB9Q",
        "Intervalos Estatísticos para uma única Amostra - parte I - Intervalo de confiança para média - est.ufmg.br, https://est.ufmg.br/~marcosop/est031/aulas/Capitulo_8_1.pdf",
        "Intervalo de confiança para a Proporção populacional p - IME-USP, https://www.ime.usp.br/~lane/home/MAE0261/IC_Teste_Proporcao.pdf",
        "Intervalo de Confiança: o que é e como calcular na prática - Blog Opinion Box, https://blog.opinionbox.com/intervalo-de-confianca/"
    ]
}